PROMPT_2_SYSTEM = """Legacy backend research prompt kept for compatibility.
The frontend-only spec workflow does not use this prompt."""

PROMPT_2_USER = """Unused in frontend-only spec mode."""

PROMPT_3_SYSTEM = """You are a senior product designer and technical writer producing a complete,
production-ready frontend specification for a mobile app clone.

Write only the frontend spec. Do not include backend architecture, APIs,
databases, infrastructure, auth implementation details, or server-side
recommendations unless they are required to explain a visible frontend flow.

Apply all branding overrides. Be thorough — this file is the sole frontend
source of truth a developer needs.
Make it explicit somewhere in the visible spec that the intended build target
is a React Native mobile app for iPhone and Android phones, not a desktop site.

Design documentation must be polished, precise, and implementation-ready.
Every color must include its hex or rgba value in backticks.
Use backticks for all technical values, including hex codes, rgba values,
pixel values, weights, radii, spacing, and shadows.
Typography must be expressed as a table with exactly these columns:
| Role | Font | Size | Weight | Line Height | Letter Spacing | Notes |
Every component spec must list exact property values for: background,
text color, border-radius, border, shadow, padding, and state changes.
Include an elevation/depth table with exactly these columns:
| Level | Treatment | Use | and cover 3-5 rows from flat through modal/overlay.
Include a responsive breakpoints table with exactly these columns:
| Name | Width | Key Changes |
After every specification table, include a "### Principles" subsection with
3-5 bullet points explaining the design rationale behind the values.
Include a "## Do's and Don'ts" section with two parallel bullet lists.
Each item must use this exact format: "**Bold principle** — reason it matters"
Use precise numeric values everywhere. Never write vague phrases like
"subtle shadow" when a numeric value can be written, such as
`0 1px 3px rgba(0,0,0,0.12)`.
A DESIGN TOKENS block is included in the frontend input. Use it as the authoritative source
for color values, typography specs, spacing, border radii, elevation, responsive rules,
and component recipes.
Do not invent or approximate design values when the DESIGN TOKENS block
provides them.
When the reference app shows emoji-like glyphs, product-category illustrations,
or decorative symbols, document them as bespoke local SVG icons or SVG
illustrations. Do not treat emoji characters as the final implementation asset.
Dissolve the DESIGN TOKENS material into the visible spec sections. Do not reproduce the raw DESIGN TOKENS block as its own visible section in the final spec."""

PROMPT_3_USER = """Produce a final frontend-only spec.md for a clone of '{reference_app}'.
Rename the app to '{your_app_name}' throughout.
Apply these branding overrides: {brand_overrides}

FRONTEND SPEC:
{frontend_spec}

The frontend input may contain a `## DESIGN TOKENS` block extracted directly
from the app frames. Use that block as the authoritative design source and map
its values into the visible sections below. do not output a standalone `## DESIGN TOKENS` section in the final spec.
When the UI shows iconography or illustrations, specify them as local SVG
assets/components instead of emoji characters.

Output exactly this structure:

# {your_app_name} — Frontend Specification
> Generated by Spectr | Reference app: {reference_app}

---

## App Overview
Summarize the product, target user, and core value proposition in 2-4 concise paragraphs.
Explicitly state in this section that the intended implementation target is a React Native mobile app for phones.

## Navigation Structure
Document the primary navigation model, route hierarchy, tab structure, and cross-screen movement patterns.

## Screen Specifications
For each important screen or route:
- purpose
- layout hierarchy from top to bottom
- key modules/sections
- primary actions
- empty / loading / error / success states
- motion or transition behavior if it is visible from the recording
- exact spacing, sizing, and alignment details when the design tokens or frames make them clear

## Shared Components
Document the reusable UI components, what screens they appear on, and the exact visual rules they follow.

## Design System
### Color Palette
Organize this section as: ### Primary, ### Surface & Background, ### Accent, ### Neutral, ### Semantic.
Format each color as: Name (`#hex`): functional role description

### Typography
Output a table with exactly these columns:
| Role | Font | Size | Weight | Line Height | Letter Spacing | Notes |
Then include ### Principles with 3-5 rationale bullets.

### Spacing & Layout
Output a token table with exactly these columns:
| Token | Value | Usage |
Also document the grid system, gutters, page padding, card padding, and major layout intervals with precise numeric values.

### Component Styles
For each major component, specify exact values for:
background, text, radius, border, shadow, padding, and states (`pressed`, `focus`, `disabled`, `selected`) where applicable.

### Elevation & Depth
Output a table with exactly these columns:
| Level | Treatment | Use |

### Responsive Breakpoints
Output a table with exactly these columns:
| Name | Width | Key Changes |

### Do's and Don'ts
Use two parallel bullet lists. Every item must follow this format:
**Bold principle** — reason it matters

### Design Principles
Write 5-7 bullets explaining the visual philosophy of the reference app.

## Frontend Implementation Notes
Give concise, opinionated notes on information architecture, route priorities, shared component extraction, and the first frontend build order.

## Claude Code Prompt
Write a concise, plain-English prompt that a developer can paste directly into Claude Code to scaffold the frontend from scratch.

The prompt must include:
- One paragraph describing what the app is and what to build
- The preferred frontend stack (bullet list, names only — no configuration or code)
- The 5 most important screens to implement first
- The shared components that must exist from day one
- A single sentence explicitly stating that this should be built as a React Native mobile app for iPhone and Android phones
- A single sentence requiring local SVG icons/illustrations instead of emoji assets
- A single sentence on local demo data / mocked data expectations
- End with: "Use the spec.md in this project as your source of truth for all screens, components, and visual rules."

Maximum 400 words. No code. No markdown headers inside the prompt itself — write it as flowing instructions.
Start this section with: "Paste everything below this line into Claude Code:"
"""

SPEC_SECTION_SYSTEM = """You are a senior product designer and technical writer producing one
section of a production-ready frontend specification for a mobile app clone.

Write only the requested section. Do not include the document title. Do not include any other top-level `##` sections.
Output markdown only, with no code
fences and no commentary.

Write only the frontend spec. Do not include backend architecture, APIs,
databases, infrastructure, auth implementation details, or server-side
recommendations unless they are required to explain a visible frontend flow.

Apply all branding overrides. Be thorough — this section must be detailed
enough to stand on its own inside the final spec.
Make it explicit somewhere in the visible spec that the intended build target
is a React Native mobile app for iPhone and Android phones, not a desktop site.

Design documentation must be polished, precise, and implementation-ready.
Every color must include its hex or rgba value in backticks.
Use backticks for all technical values, including hex codes, rgba values,
pixel values, weights, radii, spacing, and shadows.
Typography tables must use exactly these columns:
| Role | Font | Size | Weight | Line Height | Letter Spacing | Notes |
Elevation/depth tables must use exactly these columns:
| Level | Treatment | Use |
Responsive breakpoint tables must use exactly these columns:
| Name | Width | Key Changes |
A DESIGN TOKENS block is included in the frontend input. Use it as the authoritative source
for color values, typography specs, spacing, border radii, elevation, responsive rules,
and component recipes.
Do not invent or approximate design values when the DESIGN TOKENS block
provides them.
When the reference app shows emoji-like glyphs, category illustrations, or
decorative symbols, document them as bespoke local SVG icons or SVG
illustrations. Do not treat emoji characters as the final implementation asset.
Dissolve the DESIGN TOKENS material into the visible section content. Do not reproduce the raw DESIGN TOKENS block as its own visible section."""

SPEC_SECTION_DEFINITIONS = (
    {
        "key": "app_overview",
        "filename": "01-app-overview.md",
        "top_level_headings": ("## App Overview",),
        "required_substrings": ("React Native",),
        "instructions": """Output exactly one top-level section:

## App Overview

Summarize the product, target user, and core value proposition in 2-4 concise
paragraphs. The opening paragraph must explicitly state that the intended
implementation target is a React Native mobile app for iPhone and Android
phones. Keep this section tightly focused on the user-facing frontend
experience and the product promise visible in the recording.""",
    },
    {
        "key": "navigation_structure",
        "filename": "02-navigation-structure.md",
        "top_level_headings": ("## Navigation Structure",),
        "required_substrings": (),
        "instructions": """Output exactly one top-level section:

## Navigation Structure

Document the primary navigation model, route hierarchy, tab structure, modal
layers, drill-down paths, sticky headers, and cross-screen movement patterns
that are visible in the recording.""",
    },
    {
        "key": "screen_specifications",
        "filename": "03-screen-specifications.md",
        "top_level_headings": ("## Screen Specifications",),
        "required_substrings": (),
        "instructions": """Output exactly one top-level section:

## Screen Specifications

For each important screen or route, document:
- purpose
- layout hierarchy from top to bottom
- key modules and sections
- primary actions
- empty, loading, error, and success states if visible or strongly implied
- motion or transition behavior if visible in the recording
- exact spacing, sizing, and alignment details when the design tokens or frames make them clear

Use clear subheadings for each screen, but do not introduce any additional
top-level `##` sections.""",
    },
    {
        "key": "shared_components",
        "filename": "04-shared-components.md",
        "top_level_headings": ("## Shared Components",),
        "required_substrings": ("### 1.",),
        "instructions": """Output exactly one top-level section:

## Shared Components

Document the reusable UI components, what screens they appear on, and the exact
visual rules they follow. Number the components starting at `### 1.` and
increment sequentially without skipping numbers. If a component continues across
tables or prose, preserve the numbering instead of restarting.""",
    },
    {
        "key": "design_system",
        "filename": "05-design-system.md",
        "top_level_headings": ("## Design System",),
        "required_substrings": (
            "### Color Palette",
            "### Typography",
            "| Role | Font | Size | Weight | Line Height | Letter Spacing | Notes |",
            "### Spacing & Layout",
            "| Token | Value | Usage |",
            "### Component Styles",
            "### Elevation & Depth",
            "| Level | Treatment | Use |",
            "### Responsive Breakpoints",
            "| Name | Width | Key Changes |",
            "### Do's and Don'ts",
            "### Design Principles",
        ),
        "instructions": """Output exactly one top-level section:

## Design System

Within this section, include exactly these visible subsections in this order:

### Color Palette
Organize the palette as:
#### Primary
#### Surface & Background
#### Accent
#### Neutral
#### Semantic
Format each color as: Name (`#hex`): functional role description

### Typography
Output a table with exactly these columns:
| Role | Font | Size | Weight | Line Height | Letter Spacing | Notes |
Then include `### Principles` with 3-5 rationale bullets.

### Spacing & Layout
Output a token table with exactly these columns:
| Token | Value | Usage |
Also document the grid system, gutters, page padding, card padding, and major
layout intervals with precise numeric values.

### Component Styles
For each major component, specify exact values for:
background, text, radius, border, shadow, padding, and states (`pressed`,
`focus`, `disabled`, `selected`) where applicable.

### Elevation & Depth
Output a table with exactly these columns:
| Level | Treatment | Use |

### Responsive Breakpoints
Output a table with exactly these columns:
| Name | Width | Key Changes |

### Do's and Don'ts
Use two parallel bullet lists. Every item must follow this format:
**Bold principle** — reason it matters

### Design Principles
Write 5-7 bullets explaining the visual philosophy of the reference app.""",
    },
    {
        "key": "implementation_notes",
        "filename": "06-frontend-implementation-notes.md",
        "top_level_headings": ("## Frontend Implementation Notes",),
        "required_substrings": (),
        "instructions": """Output exactly one top-level section:

## Frontend Implementation Notes

Give concise, opinionated notes on information architecture, route priorities,
shared component extraction, performance-sensitive UI behavior, and the first
frontend build order. Keep the guidance practical and implementation-oriented.""",
    },
    {
        "key": "claude_code_prompt",
        "filename": "07-claude-code-prompt.md",
        "top_level_headings": ("## Claude Code Prompt",),
        "required_substrings": (
            "Paste everything below this line into Claude Code:",
            "React Native",
        ),
        "instructions": """Output exactly one top-level section:

## Claude Code Prompt

Start the section with exactly:
Paste everything below this line into Claude Code:

Then write a concise, plain-English prompt that a developer can paste directly
into Claude Code to scaffold the frontend from scratch.

The prompt must include:
- one paragraph describing what the app is and what to build
- the preferred frontend stack (bullet list, names only — no configuration or code)
- the 5 most important screens to implement first
- the shared components that must exist from day one
- one sentence explicitly stating that this should be built as a React Native mobile app for iPhone and Android phones
- a single sentence requiring local SVG icons/illustrations instead of emoji assets
- a single sentence on local demo data or mocked data expectations
- this exact closing sentence:
  Use the spec.md in this project as your source of truth for all screens, components, and visual rules.

Maximum 400 words. No code. No markdown headers inside the pasted prompt itself — write it as flowing instructions.""",
    },
)


def build_spec_section_prompt(
    *,
    section: dict,
    reference_app: str,
    your_app_name: str,
    brand_overrides: str,
    frontend_spec: str,
) -> str:
    return """Produce only `{filename}` for a frontend-only spec.md for a clone of '{reference_app}'.
Rename the app to '{your_app_name}' throughout.
Apply these branding overrides: {brand_overrides}

FRONTEND SPEC:
{frontend_spec}

The frontend input may contain a `## DESIGN TOKENS` block extracted directly
from the app frames. Use that block as the authoritative design source and map
its values into this section. Do not output a standalone `## DESIGN TOKENS`
section.
When the UI shows iconography or illustrations, specify them as local SVG
assets/components instead of emoji characters.

Do not output the document title. Do not output any top-level `##` sections
other than:
{allowed_headings}

{instructions}
""".format(
        filename=section["filename"],
        reference_app=reference_app,
        your_app_name=your_app_name,
        brand_overrides=brand_overrides,
        frontend_spec=frontend_spec,
        allowed_headings="\n".join(section["top_level_headings"]),
        instructions=section["instructions"],
    )
