import fs from 'node:fs/promises'
import path from 'node:path'
import { extractPhoneDocument } from '@/lib/extract-phone'

export const APPS = [
  'airbnb',
  'alltrails',
  'amazon',
  'apple-maps',
  'apple-music',
  'apple-notes',
  'apple-wallet',
  'audible',
  'bereal',
  'bluesky',
  'booking',
  'bumble',
  'cal-ai',
  'calm',
  'cash-app',
  'chatgpt',
  'chipotle',
  'claude',
  'coinbase',
  'copilot',
  'discord',
  'disney-plus',
  'dominos',
  'doordash',
  'dropbox',
  'duolingo',
  'ebay',
  'etsy',
  'facebook',
  'figma',
  'flighty',
  'flo',
  'gemini',
  'gmail',
  'google-calendar',
  'google-maps',
  'grindr',
  'grok',
  'headspace',
  'hinge',
  'hopper',
  'hulu',
  'instacart',
  'instagram',
  'klarna',
  'line',
  'linear',
  'linkedin',
  'lyft',
  'mastodon',
  'max',
  'messenger',
  'microsoft-teams',
  'myfitnesspal',
  'netflix',
  'nextdoor',
  'nike-run-club',
  'notion',
  'obsidian',
  'okcupid',
  'oura',
  'paypal',
  'perplexity',
  'pinterest',
  'prime-video',
  'quora',
  'reddit',
  'revolut',
  'robinhood',
  'shazam',
  'signal',
  'slack',
  'snapchat',
  'soundcloud',
  'spotify',
  'starbucks',
  'strava',
  'telegram',
  'things-3',
  'threads',
  'tidal',
  'tiktok',
  'tinder',
  'todoist',
  'trello',
  'tripadvisor',
  'tumblr',
  'twitch',
  'uber',
  'uber-eats',
  'venmo',
  'walmart',
  'waze',
  'wechat',
  'whatsapp',
  'whoop',
  'wise',
  'x-twitter',
  'youtube',
  'zoom',
  'vsco',
  'clubhouse',
  'lemon8',
  'flickr',
  'vimeo',
  'vero',
  'gas',
  'locket',
  'imessage',
  'viber',
  'skype',
  'kik',
  'groupme',
  'kakaotalk',
  'zalo',
  'threema',
  'expedia',
  'kayak',
  'vrbo',
  'marriott-bonvoy',
  'delta',
  'united-airlines',
  'southwest',
  'turo',
  'skyscanner',
  'citymapper',
  'pandora',
  'deezer',
  'youtube-music',
  'amazon-music',
  'iheartradio',
  'bandcamp',
  'pocket-casts',
  'overcast',
  'peacock',
  'paramount-plus',
  'apple-tv',
  'crunchyroll',
  'plex',
  'espn',
  'tubi',
  'pluto-tv',
  'kick',
  'grubhub',
  'deliveroo',
  'zomato',
  'swiggy',
  'mcdonalds',
  'taco-bell',
  'panera',
  'opentable',
  'resy',
  'yelp',
  'chime',
  'sofi',
  'monzo',
  'nubank',
  'acorns',
  'fidelity',
  'charles-schwab',
  'webull',
  'binance',
  'crypto-com',
  'fitbit',
  'garmin-connect',
  'peloton',
  'apple-fitness',
  'hevy',
  'strong',
  'zwift',
  'sleep-cycle',
  'noom',
  'runna',
  'asana',
  'monday',
  'clickup',
  'jira',
  'evernote',
  'bear',
  'craft',
  'miro',
  'canva',
  'grammarly',
  'coffee-meets-bagel',
  'plenty-of-fish',
  'match',
  'the-league',
  'raya',
  'feeld',
  'happn',
  'character-ai',
  'midjourney',
  'deepseek',
  'github',
  'vercel',
  'postman',
  'life360',
  'goodreads',
  'kindle',
  'substack',
] as const

export type AppSlug = (typeof APPS)[number]

export const TITLES: Record<AppSlug, string> = {
  'airbnb': 'Airbnb',
  'alltrails': 'AllTrails',
  'amazon': 'Amazon',
  'apple-maps': 'Apple Maps',
  'apple-music': 'Apple Music',
  'apple-notes': 'Apple Notes',
  'apple-wallet': 'Apple Wallet',
  'audible': 'Audible',
  'bereal': 'BeReal',
  'bluesky': 'Bluesky',
  'booking': 'Booking.com',
  'bumble': 'Bumble',
  'cal-ai': 'Cal AI',
  'calm': 'Calm',
  'cash-app': 'Cash App',
  'chatgpt': 'ChatGPT',
  'chipotle': 'Chipotle',
  'claude': 'Claude',
  'coinbase': 'Coinbase',
  'copilot': 'Microsoft Copilot',
  'discord': 'Discord',
  'disney-plus': 'Disney+',
  'dominos': "Domino's",
  'doordash': 'DoorDash',
  'dropbox': 'Dropbox',
  'duolingo': 'Duolingo',
  'ebay': 'eBay',
  'etsy': 'Etsy',
  'facebook': 'Facebook',
  'figma': 'Figma',
  'flighty': 'Flighty',
  'flo': 'Flo',
  'gemini': 'Google Gemini',
  'gmail': 'Gmail',
  'google-calendar': 'Google Calendar',
  'google-maps': 'Google Maps',
  'grindr': 'Grindr',
  'grok': 'Grok',
  'headspace': 'Headspace',
  'hinge': 'Hinge',
  'hopper': 'Hopper',
  'hulu': 'Hulu',
  'instacart': 'Instacart',
  'instagram': 'Instagram',
  'klarna': 'Klarna',
  'line': 'LINE',
  'linear': 'Linear',
  'linkedin': 'LinkedIn',
  'lyft': 'Lyft',
  'mastodon': 'Mastodon',
  'max': 'Max',
  'messenger': 'Messenger',
  'microsoft-teams': 'Microsoft Teams',
  'myfitnesspal': 'MyFitnessPal',
  'netflix': 'Netflix',
  'nextdoor': 'Nextdoor',
  'nike-run-club': 'Nike Run Club',
  'notion': 'Notion',
  'obsidian': 'Obsidian',
  'okcupid': 'OkCupid',
  'oura': 'Oura',
  'paypal': 'PayPal',
  'perplexity': 'Perplexity',
  'pinterest': 'Pinterest',
  'prime-video': 'Prime Video',
  'quora': 'Quora',
  'reddit': 'Reddit',
  'revolut': 'Revolut',
  'robinhood': 'Robinhood',
  'shazam': 'Shazam',
  'signal': 'Signal',
  'slack': 'Slack',
  'snapchat': 'Snapchat',
  'soundcloud': 'SoundCloud',
  'spotify': 'Spotify',
  'starbucks': 'Starbucks',
  'strava': 'Strava',
  'telegram': 'Telegram',
  'things-3': 'Things 3',
  'threads': 'Threads',
  'tidal': 'TIDAL',
  'tiktok': 'TikTok',
  'tinder': 'Tinder',
  'todoist': 'Todoist',
  'trello': 'Trello',
  'tripadvisor': 'Tripadvisor',
  'tumblr': 'Tumblr',
  'twitch': 'Twitch',
  'uber': 'Uber',
  'uber-eats': 'Uber Eats',
  'venmo': 'Venmo',
  'walmart': 'Walmart',
  'waze': 'Waze',
  'wechat': 'WeChat',
  'whatsapp': 'WhatsApp',
  'whoop': 'WHOOP',
  'wise': 'Wise',
  'x-twitter': 'X (Twitter)',
  'youtube': 'YouTube',
  'zoom': 'Zoom',
  'vsco': 'VSCO',
  'clubhouse': 'Clubhouse',
  'lemon8': 'Lemon8',
  'flickr': 'Flickr',
  'vimeo': 'Vimeo',
  'vero': 'Vero',
  'gas': 'Gas',
  'locket': 'Locket',
  'imessage': 'iMessage',
  'viber': 'Viber',
  'skype': 'Skype',
  'kik': 'Kik',
  'groupme': 'GroupMe',
  'kakaotalk': 'KakaoTalk',
  'zalo': 'Zalo',
  'threema': 'Threema',
  'expedia': 'Expedia',
  'kayak': 'KAYAK',
  'vrbo': 'Vrbo',
  'marriott-bonvoy': 'Marriott Bonvoy',
  'delta': 'Delta',
  'united-airlines': 'United',
  'southwest': 'Southwest',
  'turo': 'Turo',
  'skyscanner': 'Skyscanner',
  'citymapper': 'Citymapper',
  'pandora': 'Pandora',
  'deezer': 'Deezer',
  'youtube-music': 'YouTube Music',
  'amazon-music': 'Amazon Music',
  'iheartradio': 'iHeartRadio',
  'bandcamp': 'Bandcamp',
  'pocket-casts': 'Pocket Casts',
  'overcast': 'Overcast',
  'peacock': 'Peacock',
  'paramount-plus': 'Paramount+',
  'apple-tv': 'Apple TV',
  'crunchyroll': 'Crunchyroll',
  'plex': 'Plex',
  'espn': 'ESPN',
  'tubi': 'Tubi',
  'pluto-tv': 'Pluto TV',
  'kick': 'Kick',
  'grubhub': 'Grubhub',
  'deliveroo': 'Deliveroo',
  'zomato': 'Zomato',
  'swiggy': 'Swiggy',
  'mcdonalds': "McDonald's",
  'taco-bell': 'Taco Bell',
  'panera': 'Panera',
  'opentable': 'OpenTable',
  'resy': 'Resy',
  'yelp': 'Yelp',
  'chime': 'Chime',
  'sofi': 'SoFi',
  'monzo': 'Monzo',
  'nubank': 'Nubank',
  'acorns': 'Acorns',
  'fidelity': 'Fidelity',
  'charles-schwab': 'Charles Schwab',
  'webull': 'Webull',
  'binance': 'Binance',
  'crypto-com': 'Crypto.com',
  'fitbit': 'Fitbit',
  'garmin-connect': 'Garmin Connect',
  'peloton': 'Peloton',
  'apple-fitness': 'Apple Fitness',
  'hevy': 'Hevy',
  'strong': 'Strong',
  'zwift': 'Zwift',
  'sleep-cycle': 'Sleep Cycle',
  'noom': 'Noom',
  'runna': 'Runna',
  'asana': 'Asana',
  'monday': 'Monday.com',
  'clickup': 'ClickUp',
  'jira': 'Jira',
  'evernote': 'Evernote',
  'bear': 'Bear',
  'craft': 'Craft',
  'miro': 'Miro',
  'canva': 'Canva',
  'grammarly': 'Grammarly',
  'coffee-meets-bagel': 'Coffee Meets Bagel',
  'plenty-of-fish': 'Plenty of Fish',
  'match': 'Match',
  'the-league': 'The League',
  'raya': 'Raya',
  'feeld': 'Feeld',
  'happn': 'happn',
  'character-ai': 'Character.AI',
  'midjourney': 'Midjourney',
  'deepseek': 'DeepSeek',
  'github': 'GitHub',
  'vercel': 'Vercel',
  'postman': 'Postman',
  'life360': 'Life360',
  'goodreads': 'Goodreads',
  'kindle': 'Kindle',
  'substack': 'Substack',
}

export function isAppSlug(slug: string): slug is AppSlug {
  return (APPS as readonly string[]).includes(slug)
}

export function specGithubUrl(slug: AppSlug): string {
  return `https://github.com/Meliwat/awesome-ios-design-md/tree/main/design-md/${slug}`
}

const PREVIEWS_DIR = path.join(process.cwd(), 'previews-private')

export async function fetchPhone(slug: AppSlug): Promise<string | null> {
  try {
    const filePath = path.join(PREVIEWS_DIR, slug, 'index.html')
    const raw = await fs.readFile(filePath, 'utf8')
    return extractPhoneDocument(raw)
  } catch {
    return null
  }
}
