import type { AppSlug } from './apps'

export const CATEGORIES = [
  'social',
  'messaging',
  'travel',
  'music',
  'video',
  'food',
  'finance',
  'fitness',
  'productivity',
  'dating',
  'misc',
] as const

export type CategorySlug = (typeof CATEGORIES)[number]

export const CATEGORY_LABELS: Record<CategorySlug, string> = {
  social: 'Social',
  messaging: 'Messaging',
  travel: 'Travel',
  music: 'Music',
  video: 'Video',
  food: 'Food',
  finance: 'Finance',
  fitness: 'Fitness',
  productivity: 'Productivity',
  dating: 'Dating',
  misc: 'Misc',
}

export const CATEGORY_APPS: Record<CategorySlug, AppSlug[]> = {
  social: [
    'instagram',
    'tiktok',
    'x-twitter',
    'threads',
    'facebook',
    'snapchat',
    'reddit',
    'pinterest',
    'linkedin',
    'bereal',
    'mastodon',
    'bluesky',
    'nextdoor',
    'tumblr',
    'quora',
    'vsco',
    'clubhouse',
    'lemon8',
    'flickr',
    'vimeo',
    'vero',
    'gas',
    'locket',
  ],
  messaging: [
    'whatsapp',
    'telegram',
    'discord',
    'slack',
    'signal',
    'messenger',
    'line',
    'wechat',
    'imessage',
    'viber',
    'skype',
    'kik',
    'groupme',
    'kakaotalk',
    'zalo',
    'threema',
  ],
  travel: [
    'airbnb',
    'uber',
    'google-maps',
    'apple-maps',
    'waze',
    'lyft',
    'booking',
    'tripadvisor',
    'hopper',
    'flighty',
    'expedia',
    'kayak',
    'vrbo',
    'marriott-bonvoy',
    'delta',
    'united-airlines',
    'southwest',
    'turo',
    'skyscanner',
    'citymapper',
  ],
  music: [
    'spotify',
    'apple-music',
    'soundcloud',
    'tidal',
    'shazam',
    'audible',
    'pandora',
    'deezer',
    'youtube-music',
    'amazon-music',
    'iheartradio',
    'bandcamp',
    'pocket-casts',
    'overcast',
  ],
  video: [
    'youtube',
    'netflix',
    'disney-plus',
    'hulu',
    'max',
    'twitch',
    'prime-video',
    'peacock',
    'paramount-plus',
    'apple-tv',
    'crunchyroll',
    'plex',
    'espn',
    'tubi',
    'pluto-tv',
    'kick',
  ],
  food: [
    'doordash',
    'starbucks',
    'uber-eats',
    'instacart',
    'chipotle',
    'dominos',
    'grubhub',
    'deliveroo',
    'zomato',
    'swiggy',
    'mcdonalds',
    'taco-bell',
    'panera',
    'opentable',
    'resy',
    'yelp',
  ],
  finance: [
    'venmo',
    'cash-app',
    'paypal',
    'robinhood',
    'coinbase',
    'apple-wallet',
    'etsy',
    'ebay',
    'walmart',
    'revolut',
    'wise',
    'klarna',
    'chime',
    'sofi',
    'monzo',
    'nubank',
    'acorns',
    'fidelity',
    'charles-schwab',
    'webull',
    'binance',
    'crypto-com',
  ],
  fitness: [
    'strava',
    'nike-run-club',
    'headspace',
    'myfitnesspal',
    'whoop',
    'calm',
    'oura',
    'flo',
    'alltrails',
    'fitbit',
    'garmin-connect',
    'peloton',
    'apple-fitness',
    'hevy',
    'strong',
    'zwift',
    'sleep-cycle',
    'noom',
    'runna',
  ],
  productivity: [
    'notion',
    'figma',
    'apple-notes',
    'todoist',
    'google-calendar',
    'trello',
    'linear',
    'zoom',
    'microsoft-teams',
    'things-3',
    'obsidian',
    'dropbox',
    'asana',
    'monday',
    'clickup',
    'jira',
    'evernote',
    'bear',
    'craft',
    'miro',
    'canva',
    'grammarly',
  ],
  dating: [
    'tinder',
    'hinge',
    'bumble',
    'grindr',
    'okcupid',
    'coffee-meets-bagel',
    'plenty-of-fish',
    'match',
    'the-league',
    'raya',
    'feeld',
    'happn',
  ],
  misc: [
    'chatgpt',
    'claude',
    'perplexity',
    'gmail',
    'amazon',
    'cal-ai',
    'duolingo',
    'gemini',
    'copilot',
    'grok',
    'character-ai',
    'midjourney',
    'deepseek',
    'github',
    'vercel',
    'postman',
    'life360',
    'goodreads',
    'kindle',
    'substack',
  ],
}

export function isCategorySlug(slug: string): slug is CategorySlug {
  return (CATEGORIES as readonly string[]).includes(slug)
}

// Reverse lookup: app slug → its category. Null for an unmapped slug.
export function categoryForApp(slug: string): CategorySlug | null {
  for (const cat of CATEGORIES) {
    if ((CATEGORY_APPS[cat] as readonly string[]).includes(slug)) return cat
  }
  return null
}

// Public design-md repo where every app's free DESIGN.md + framework guides live.
export const DESIGN_REPO = 'https://github.com/Meliwat/awesome-ios-design-md'

// Link to one app's folder (all 4 framework files + its README index).
export function appSpecRepoUrl(category: string, slug: string): string {
  return `${DESIGN_REPO}/tree/main/design-md/${category}/${slug}`
}

// Link to a whole category's folder.
export function categorySpecRepoUrl(category: string): string {
  return `${DESIGN_REPO}/tree/main/design-md/${category}`
}
