import type { AppSlug } from './apps'

export const CATEGORIES = [
  'social',
  'messaging',
  'travel',
  'music',
  'video',
  'food',
  'finance',
  'fitness',
  'productivity',
  'dating',
  'misc',
] as const

export type CategorySlug = (typeof CATEGORIES)[number]

export const CATEGORY_LABELS: Record<CategorySlug, string> = {
  social: 'Social',
  messaging: 'Messaging',
  travel: 'Travel',
  music: 'Music',
  video: 'Video',
  food: 'Food',
  finance: 'Finance',
  fitness: 'Fitness',
  productivity: 'Productivity',
  dating: 'Dating',
  misc: 'Misc',
}

export const CATEGORY_APPS: Record<CategorySlug, AppSlug[]> = {
  social: [
    'instagram',
    'tiktok',
    'x-twitter',
    'threads',
    'facebook',
    'snapchat',
    'reddit',
    'pinterest',
    'linkedin',
    'bereal',
    'mastodon',
    'bluesky',
    'nextdoor',
    'tumblr',
    'quora',
  ],
  messaging: ['whatsapp', 'telegram', 'discord', 'slack', 'signal', 'messenger', 'line', 'wechat'],
  travel: [
    'airbnb',
    'uber',
    'google-maps',
    'apple-maps',
    'waze',
    'lyft',
    'booking',
    'tripadvisor',
    'hopper',
    'flighty',
  ],
  music: ['spotify', 'apple-music', 'soundcloud', 'tidal', 'shazam', 'audible'],
  video: ['youtube', 'netflix', 'disney-plus', 'hulu', 'max', 'twitch', 'prime-video'],
  food: ['doordash', 'starbucks', 'uber-eats', 'instacart', 'chipotle', 'dominos'],
  finance: [
    'venmo',
    'cash-app',
    'paypal',
    'robinhood',
    'coinbase',
    'apple-wallet',
    'etsy',
    'ebay',
    'walmart',
    'revolut',
    'wise',
    'klarna',
  ],
  fitness: [
    'strava',
    'nike-run-club',
    'headspace',
    'myfitnesspal',
    'whoop',
    'calm',
    'oura',
    'flo',
    'alltrails',
  ],
  productivity: [
    'notion',
    'figma',
    'apple-notes',
    'todoist',
    'google-calendar',
    'trello',
    'linear',
    'zoom',
    'microsoft-teams',
    'things-3',
    'obsidian',
    'dropbox',
  ],
  dating: ['tinder', 'hinge', 'bumble', 'grindr', 'okcupid'],
  misc: [
    'chatgpt',
    'claude',
    'perplexity',
    'gmail',
    'amazon',
    'cal-ai',
    'duolingo',
    'gemini',
    'copilot',
    'grok',
  ],
}

export function isCategorySlug(slug: string): slug is CategorySlug {
  return (CATEGORIES as readonly string[]).includes(slug)
}
