PROMPT_1_SYSTEM = """You are an expert mobile app reverse-engineer and technical product manager.
Analyze the provided screenshots and document every screen in exhaustive detail.
A developer reading your output should never need to guess at anything."""

PROMPT_1_USER = """These {n} screenshots are from the app '{reference_app}'.

For each distinct screen visible, output:

## Screen: [Name]
**Purpose:** What this screen does for the user
**Route:** e.g. /home, /profile/:id, /settings/notifications
**Layout:** Overall structure (tabs, lists, cards, grids, etc.)
**Components:** Every visible element — name, type, content, tap behavior
**Data Shown:** What data is displayed and in what shape
**Navigation:** What screens are reachable from here and how
**States:** Loading, empty, error, or conditional states visible
**UX Notes:** Animations, gestures, notable edge cases

Merge screenshots that show the same screen.
Output screen specs only — no preamble, no closing remarks."""

PROMPT_2_SYSTEM = """You are a senior backend architect who specializes in reverse-engineering
app architectures from public information.

Use the web_search tool to research the app before writing your spec.
Search for: engineering blogs, tech stack pages, job postings, API docs,
GitHub repos, conference talks, and technical breakdowns.

Label every claim as:
  [CONFIRMED — <source URL>]  when found in a public source
  [INFERRED — <reasoning>]    when reasoned from UI patterns or industry norms"""

PROMPT_2_USER = """Research and document the backend architecture for '{reference_app}'.

Also consider what was observed in the UI:
{frontend_summary}

Produce a backend specification with these sections:

## Tech Stack
## API Architecture (REST/GraphQL/WebSocket, key endpoints)
## Data Models (core entities and relationships)
## Authentication & Authorization
## Key Third-Party Integrations
## Infrastructure & Deployment
## Scalability Patterns
## Implementation Notes for Cloning

For each item include a [CONFIRMED] or [INFERRED] label.

Close with a '## Recommended Stack for Clone' section with concrete, opinionated choices."""

PROMPT_3_SYSTEM = """You are a technical writer producing a complete, production-ready app specification.
Combine the frontend and backend specs into one clean structured spec.md.
Apply all branding overrides. Be thorough — this file is the sole input a developer needs."""

PROMPT_3_USER = """Produce a final spec.md for a clone of '{reference_app}'.
Rename the app to '{your_app_name}' throughout.
Apply these branding overrides: {brand_overrides}

FRONTEND SPEC:
{frontend_spec}

BACKEND SPEC:
{backend_spec}

Output exactly this structure:

# {your_app_name} — Full Stack Specification
> Generated by Spectr | Reference app: {reference_app}

---

# PART 1: FRONTEND

## App Overview
## Navigation Structure
## Screen Specifications
## Shared Components
## Design System

---

# PART 2: BACKEND

## Tech Stack
## API Architecture
## Data Models
## Authentication
## Third-Party Integrations
## Infrastructure
## Implementation Notes
## Recommended Stack for Clone

---

# PART 3: CLAUDE CODE PROMPT

Provide a complete, self-contained prompt the user can paste directly into Claude Code
to scaffold this entire app from scratch. Reference key screens, data models, the recommended
stack, and instruct Claude Code to build as much as possible in one shot.
Start this section with: "Paste everything below this line into Claude Code:"
"""
